name: $(GITVERSION_SemVer)

trigger:
- release/*
- develop
- main

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'

steps:

- task: NuGetInstaller@0
  displayName: 'Use NuGet'
  
- checkout: self
  fetchDepth: 0

- task: gitversion/setup@0
  displayName: Setup GitVersion
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  displayName: Execute GitVersion

- task: NuGetCommand@2
  displayName: 'NuGet restore'

- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    clean: true
    solution: '**\*.sln'
    configuration: 'release'
    msbuildArchitecture: 'x64'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/$(Build.DefinitionName)/*.csproj'
    packDirectory: 'artifacts'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'GITVERSION_NuGetVersion'
    configuration: 'release'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './artifacts'
    ArtifactName: 'drop'
    TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'


